### ISSUE TITLE
get entire config at once?

### ISSUE THREAD

**Issue by techieshark** [fredriks/cloud-functions-runtime-config#11]
Currently, `getVariables()` is great but it calls `getVariable()` repeatedly (which, side effect, also calls auth repeatedly). So it looks like one call could generate 2*N network hits, for N variables.

It's possible to return all variables at once:

https://cloud.google.com/deployment-manager/runtime-configurator/set-and-get-variables#getting_a_variables_value

https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/v1beta1/projects.configs.variables/

Possible feature request then would be perhaps a method like `listVariables(returnValues: true|false)` which could return something like

[ [object(Variable)](https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/v1beta1/projects.configs.variables#Variable) ]

possibly with `name` on objects changed to just the varname, or a `variableName` property added that has just the var name (not the fully qualified name). 

For a small config, this would be 1 auth network hit + 1 config network hit. For larger configs, the results are paged so additional config network hits for each page.

**Comment by fredriks** [comment]
That's a great point, thanks for reporting this!

`list` is supported [upstream](https://github.com/google/google-api-nodejs-client/blob/v27.0.0/src/apis/runtimeconfig/v1beta1.ts#L529-L568) so it fits well with this being a small wrapper around [googleapis](https://github.com/google/google-api-nodejs-client) and could be implemented similar to `getVariable`.

Additional network requests for multiple calls to `auth()` could potentially be considered a bug. Maybe this could be handled within [Google Auth Library](https://github.com/google/google-auth-library-nodejs) by interacting with it differently or maybe the authClient could be cached but then there have to be invalidation checks.
